server:
  port: 8080

payment:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  base-url: https://api.tosspayments.com/v1/payments
  confirm-endpoint: /confirm
  connect-timeout: 1000
  read-timeout: 30000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/pretallez
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    commandTimeout: 60000
    shutdownTimeout: 2000

  # data.sql 실행 옵션
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: odjoaiwdjawodjaiowjdioawjdioawjdiowajdoajdoiwj