spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pretallez
    username: pretallezuser
    password: pretallezpw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update  # 스키마 자동 생성 (운영 환경에서는 `validate` 권장)
    show-sql: true  # SQL 로그 출력 여부
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅

