server:
  port: ${SERVER_PORT}

payment:
  secret-key: ${SECRET_KEY}
  base-url: ${BASE_URL}
  confirm-endpoint: ${CONFIRM_ENDPOINT}
  connect-timeout: 1000
  read-timeout: 30000

spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  redis:
    host: ${HOST}
    port: ${PORT}
    commandTimeout: 60000
    shutdownTimeout: 2000

  # data.sql 실행을 위한 설정
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: ${DATABASE_PLATFORM}
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET_KEY}