server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/pretallez_local
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  flyway:
    schemas:
      - pretallez_local
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    stompPort: 61613  # 예시 포트 (STOMP over TCP의 기본값은 61613)
    destinationPrefix: /topic
    appDestinationPrefix: /app
    chat:
      exchange: chat.exchange
      queue: chat.queue
      routingKey: chat.key

  redis:
    host: 127.0.0.1
    port: 6379

oauth:
  kakao:
    redirect-url: http://localhost:8080
    clientId:

jwt:
  secret: asdsafmsdajkgnjaksdngjkasdngkjdsangkdnsakgndsakjgdsagsdag